Added Ubuntu 18.04
karras/cloud-linux-images pull request #1
Opened 2020-06-03 13:03 UTC by rhomson2

2020-06-03 15:20 UTC, karras commented
As discussed, thanks a lot for the hard work! What do you think about my comments / proposals?

2020-06-03 15:20 UTC, karras requested changes

2020-06-03 15:20 UTC, karras commented on provisioning/ubuntu1804_preseed.cfg
> +d-i pkgsel/upgrade select full-upgrade
Please add a new line at the end of the file :)

2020-06-03 15:20 UTC, karras commented on provisioning/ubuntu1804_preseed.cfg
> +d-i passwd/user-password password rootpw
Please use hashed and not plaintext passwords

2020-06-03 15:20 UTC, karras commented on provisioning/ubuntu1804_preseed.cfg
> +d-i keyboard-configuration/xkb-keymap select de-CH
Please switch to the `en` / `us` keyboard layout thus we are aligned with the other existing images

2020-06-03 15:20 UTC, karras commented on provisioning/ubuntu1804_preseed.cfg
> +d-i pkgsel/include string openssh-server build-essential open-vm-tools
Ideally remove the `open-vm-tools` as the target hypervisor for such images is not always VMWare

2020-06-04 10:01 UTC, rhomson2 commented
Added your propositions.
Also added PROXMOX Support for Ubuntu 18.04 and 20.04

2020-06-05 05:02 UTC, karras approved these changes

2020-06-05 05:02 UTC, karras commented
Thanks :1st_place_medal:

2020-06-05 05:02 UTC, merged